### ISSUE TITLE
Quality Gems being stored in map tabs

### ISSUE THREAD

**Issue by DetectiveSquirrel** [nymann/Stashie#13]
Only quality gems are being stored in map tabs and not in the gem tab, some quality gems arnt even put into the map tab either (not full)

Tab Settings
http://puu.sh/wmc5w/348594dfcb.jpg

Map Settings
http://puu.sh/wmc80/023c22bfc0.jpg

**Comment by DetectiveSquirrel** [comment]
Just witnessed it putting the quality gems into map tab and then took them out again and it stopped there

**Comment by nymann** [comment]
@DetectiveSquirrel, quality gem settings are stored in vendor recipes. And if you have sorting enabled and there is space enough to put the items from the current stash tab into the inventory, it will sort them that way (since ctrl+leftclick'ing them in the right order was an easy way of implementing sorting), I'm gonna try and implement "real" sorting today (see issue #2).

Thanks for your feedback 👍
